### ISSUE TITLE
Load order error

### ISSUE THREAD

**Issue by iangreenleaf** [eigenben/ruby_transform#1]
I'm getting the following error (when rspecify tries to load this library):

```
/usr/lib64/ruby/gems/1.8/gems/ruby_transform-0.1.2/lib/ruby_transform/transformer.rb:8: uninitialized constant RubyTransform::Transformer::TransformerHelpers (NameError)
  from /usr/lib64/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
  from /usr/lib64/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
  from /usr/lib64/ruby/gems/1.8/gems/ruby_transform-0.1.2/lib/ruby_transform.rb:9
  from /usr/lib64/ruby/gems/1.8/gems/ruby_transform-0.1.2/lib/ruby_transform.rb:7:in `each'
  from /usr/lib64/ruby/gems/1.8/gems/ruby_transform-0.1.2/lib/ruby_transform.rb:7
  <snip>
```

It looks like the wildcard `"ruby_transform/**/**/*.rb"` is choosing `transformer.rb` before `transform_helpers.rb`, for whatever reason.

**Comment by eigenben** [comment]
Thanks - I fixed this by adding an explicit require for `TransformerHelpers` at the top of `Transformer` (always a good practice anyways) and fixed the naming inconsistency between transform_helper.rb and transformer_helper.rb. New gem version released 0.1.3.
